### ISSUE TITLE
用导出的trt模型infer，am模型推理后mel_post的值全部为nan 

### ISSUE THREAD

**Issue by kli017** [xiaomingnio/kantts#11]
环境Ubuntu18.04, python3.7.16 tensorrt 8.4.3.1
您好，按照步骤成功生成了trt模型并且可以完成demo中的pipeline生成音频，但是试听了一下，音频全为空白。debug了一下发现am_synthesis后mel_post的值全部为nan。如图。
![image](https://github.com/xiaomingnio/kantts/assets/14877573/29c92f0a-29b2-429f-a592-4967e64fdcd8)
log1.txt log2.txt是生成mel_decode engine的输出日志，不知道哪里的问题，求助。
[log1.txt](https://github.com/xiaomingnio/kantts/files/13699170/log1.txt)
[log2.txt](https://github.com/xiaomingnio/kantts/files/13699171/log2.txt)

**Comment by LumenForgeX** [comment]
重新拉一下代码试试

**Comment by kli017** [comment]
重拉了下还是一样。。但是换了台机器就好了。奇怪，难到卡的问题？
