### ISSUE TITLE
sambert导出onnx

### ISSUE THREAD

**Issue by Leslie-Tsui** [xiaomingnio/kantts#3]
作者您好，请问有sambert导出onnx的脚步吗？

**Comment by LumenForgeX** [comment]
sambert 无法导出onnx，目前只能用tensorrt api重写sambert部分代码进行加速。

**Comment by Leslie-Tsui** [comment]
> sambert 无法导出onnx，目前只能用tensorrt api重写sambert部分代码进行加速。

谢谢，但我对这方面的工作不是很熟悉，请问能提供tensorrt重写的代码吗？

**Comment by xiaomingnio** [comment]
[build_from_network.txt](https://github.com/xiaomingnio/kantts/files/13486714/build_from_network.txt)

[sambert_convert_weights.txt](https://github.com/xiaomingnio/kantts/files/13486723/sambert_convert_weights.txt)
这是搭建的脚本以及生成wts的脚本

**Comment by LumenForgeX** [comment]
后面有时间会更新完整代码

**Comment by LumenForgeX** [comment]
https://github.com/xiaomingnio/kantts/blob/main/tensorrt_onnx/build_from_network.py
