### ISSUE TITLE
请问有测过改写前后的效率吗？

### ISSUE THREAD

**Issue by lancelee98** [xiaomingnio/kantts#7]
请问有测过改写前后的效率吗？如果想并发部署的话你这边有啥建议吗？

**Comment by LumenForgeX** [comment]
3060显卡加速比大概是50%。
针对并发问题，开启多个TTS服务，利用nginx进行轮训，达到负载均衡的效果。

**Comment by lancelee98** [comment]
感谢~

**Comment by lancelee98** [comment]
@xiaomingnio  我测试了一下 T4 GPU，输入是260字时优化前14s 优化后9s左右 
前端=1.3s
am=7.9s
voc=0.5s 
还是am太耗时了

`之前我试过am推理时进行批量推理，速度会快一些。但是批量推理需要MultiHeadPNCAAttention模块做相应修改进行支持，目前我看你转成TensorRT的MultiHeadPNCAAttention其实并不支持批量推理的。
